CREATE DATABASE BED2025;
USE BED2025;
DROP DATABASE BED2025;

-- BASIC QUESTIONS 
-- SHOW ALL UNIQUE VALUES FROM STATUS COLUMN

SELECT DISTINCT Status
FROM `machine-readable-business-employment-data-dec-2025-quarter`;

-- FIND TOTAL NUMBER OF RECORDS FOR EACH UNIT TYPES

SELECT UNITS , COUNT(*) AS TOTAL_RECORDS
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY UNITS;

-- DISPLAY ALL RECORDS WHERE SUPPRESSED IS NOT NULL

SELECT * 
FROM `machine-readable-business-employment-data-dec-2025-quarter`
WHERE SUPPRESSED IS NOT NULL;

-- FIND TOP 10 HIGHEST DATA_VALUES RECORDS WITH THEIR SERIES_TITLE_1

SELECT DATA_VALUE,SERIES_TITLE_1
FROM `machine-readable-business-employment-data-dec-2025-quarter`
ORDER BY DATA_VALUE DESC
LIMIT 10;

-- COUNT HOW MANY RECORDS EXIST FOR EACH GROUP

SELECT `GROUP`, COUNT(*) AS TOTAL_RECORDS
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY `GROUP`;
 
-- SHOW RECORDS WHERE MAGNITUDE IS GREATER THAN 3

SELECT *
FROM `machine-readable-business-employment-data-dec-2025-quarter`
WHERE MAGNITUDE > 3;

-- INTERMEDIATE QUESTIONS 

-- CALCULATE AVERAGE DATA_VALUES FOR EACH SERIES_TITLE_1

SELECT SERIES_TITLE_1 , AVG(DATA_VALUE) AS AVG_VALUE
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY SERIES_TITLE_1;

-- FIND TOTAL DATA_VALUES FOR EACH PERIOD

SELECT PERIOD , SUM(DATA_VALUE) AS TOTAL_VALUES
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY PERIOD
ORDER BY PERIOD;

-- DISPLAY GROUP HAVING HIGHEST TOTAL DATA_VALUE

SELECT `GROUP` , SUM(DATA_VALUE) AS TOTAL_VALUE
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY `GROUP`
ORDER BY `GROUP` DESC
LIMIT 1;

-- COMPARE TOTAL DATA_VALUE BASED ON STATUS

SELECT `STATUS`, SUM(DATA_VALUE) AS TOTAL_VALUE
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY `STATUS`;

-- FIND TOP 5 SERIES_TITLE_2 CATEGORIES WITH HIGHEST AVERAGE DATA VALUES 

SELECT SERIES_TITLE_2 , AVG(DATA_VALUE) AS AVG_VALUE
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY SERIES_TITLE_2
ORDER BY SERIES_TITLE_2 DESC
LIMIT 5;

-- ANALYZE YEARLY TREND OF DATA_VALUE USING PERIOD

SELECT FLOOR(PERIOD) , SUM(DATA_VALUE) AS YEARLY_TOTAL
FROM `machine-readable-business-employment-data-dec-2025-quarter`
GROUP BY FLOOR(PERIOD);
